# Generated by Django 4.1 on 2022-08-25 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date_exp',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 14, 19, 2, 875962), verbose_name='Date Expiration'),
        ),
        migrations.AlterField(
            model_name='board',
            name='date_start',
            field=models.DateField(auto_now=True, verbose_name='Date Start'),
        ),
    ]
