# Generated by Django 4.1 on 2022-08-25 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_date_exp_alter_board_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date_exp',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 14, 28, 44, 344616), verbose_name='Date Expiration'),
        ),
        migrations.AlterField(
            model_name='board',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 14, 28, 44, 344616), verbose_name='Date Start'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='To Do Title')),
                ('completed', models.BooleanField(verbose_name='Completed')),
                ('date_start', models.DateField(default=datetime.datetime(2022, 8, 25, 14, 28, 44, 345613), verbose_name='Date Start')),
                ('date_exp', models.DateField(verbose_name='Date Expiration')),
                ('markdown', models.TextField(blank=True, max_length=400, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
