# Generated by Django 4.1 on 2022-08-25 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_date_exp_alter_board_date_start_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 5, 29, 39, 614675, tzinfo=datetime.timezone.utc), verbose_name='Date Start'),
        ),
        migrations.AlterField(
            model_name='board',
            name='date_exp',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 5, 29, 39, 613676, tzinfo=datetime.timezone.utc), verbose_name='Date Expiration'),
        ),
        migrations.AlterField(
            model_name='board',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 5, 29, 39, 613676, tzinfo=datetime.timezone.utc), verbose_name='Date Start'),
        ),
    ]
